### ISSUE TITLE
Publication order gets jumbled up when more than 7 publications in a particular year

### ISSUE THREAD

**Issue by bhatiasiddharth** [alshedivat/al-folio#107]
**Acknowledge the following**
- [*] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [*] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [*] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**
Whenever the number of publications in any particular year is increased to more than 7, the order does not remain same as papers.bib

**Comment by alshedivat** [comment]
Thanks for reporting this bug! Interesting, I haven't seen this happening before. Could you point me to some code for reproducing this bug?

**Comment by bhatiasiddharth** [comment]
Just add 8 publications with same year in papers.bib file within _bibliography folder.

**Comment by alshedivat** [comment]
Looks like I can reproduce the issue (see below). I think the problem might be with [jekyll-scholar](https://github.com/inukshuk/jekyll-scholar) and how it sorts/filters bibliography items rather than al-folio. I suggest raise an issue with them, reference to this one, and see what they say.

<img width="643" alt="Screen Shot 2020-08-26 at 8 29 23 AM" src="https://user-images.githubusercontent.com/2126561/91303639-4d76a600-e776-11ea-8993-e24cd0c69c99.png">
<img width="643" alt="Screen Shot 2020-08-26 at 8 29 00 AM" src="https://user-images.githubusercontent.com/2126561/91303649-50719680-e776-11ea-8171-a228af30f402.png">

**Comment by bhatiasiddharth** [comment]
Thanks, I raised an issue with them.

**Comment by bhatiasiddharth** [comment]
sort_by can be left empty and it will have the original order right now. Please check https://github.com/inukshuk/jekyll-scholar/issues/314
