### ISSUE TITLE
How to edit the font size in social.html?

### ISSUE THREAD

**Issue by xkcococo** [alshedivat/al-folio#1100]
**Acknowledge the following**
- [yes] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [yes] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [yes] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

Thank you for this wonderful template!

I was wondering how to adjust the font size in social.html? It is too big for me. The file _base.scss can only adjust the icon size, so I treid to adjust the size by the codes `font size=2px`, but it does not work. 

Thanks in advanced!
![image](https://user-images.githubusercontent.com/43758155/211937757-2e875feb-3d1c-4211-a6a1-b7f5265268bc.png)

**Comment by george-gca** [comment]
[This line](https://github.com/alshedivat/al-folio/blob/59308f4e8292a866beda7e80c8f317eb885d6405/_sass/_base.scss#L256) is what you were looking for.

**Comment by jmrplens** [comment]
The HTML code is in the file `_layouts/about.html`:

```html
<!-- Social -->
          {%- if page.social %}
            <div class="social">
              <div class="contact-icons">
                {% include social.html %}
              </div>

              <div class="contact-note">
                {{ site.contact_note }}
              </div>

            </div>
          {%- endif %}
```
You can change the `contact-icons` font size with:
```css
.social .contact-icons {
    font-size: 2rem;
}
```

**Comment by janxkoci** [comment]
I don't have `_layouts/about.html` in my [repo](https://github.com/flegontovlab/flegontovlab.github.io), only `_layouts/about.liquid`. Either way, I don't know where _exactly_ should I add the code to change size (nor what those units are).

I use jekyll _because_ I don't know much about HTML/CSS, so clearer instructions would help tremendously!

PS: I actually want to change the size of icons, they are way too huge. I've found https://github.com/alshedivat/al-folio/discussions/2386, which was simply marked as duplicate of this issue.

PPS: I'm guessing the right place to adjust the code is in `_sass/base.scss`, where I've found this block:

https://github.com/flegontovlab/flegontovlab.github.io/blob/main/_sass/_base.scss#L403-L422

But I'm not sure if I should change just the line 404, or also the following lines (e.g. 408-410, and so on).

**Comment by george-gca** [comment]
`_layouts/about.html` is the previous name of the file `_layouts/about.liquid`. We kept the same name, just changed the extension so that code editors can correctly display the syntax highlight.
About the line, it is the same line

https://github.com/alshedivat/al-folio/blob/db2a1d1b1984d00a52b0be1cb74b2b3aefb31ad5/_sass/_base.scss#L404

as before

https://github.com/alshedivat/al-folio/blob/59308f4e8292a866beda7e80c8f317eb885d6405/_sass/_base.scss#L256

you can see it moved a bit since I answered that before because there was a lot of code changes since then. The line sets `font-size` because these icons are actually a font inside our code (for example, [FontAwesome](https://fontawesome.com/)).

About the units, this is css code. [Here](https://www.sitepoint.com/understanding-and-using-rem-units-in-css/) is an explanation of how it works

**Comment by janxkoci** [comment]
So changing only that one line is enough, great! 😁 Thanks! `2rem` looks much better IMHO, consider setting it as default (`4rem` is really ~~overkill~~ oversized).
