### ISSUE TITLE
Migration to Hugo

### ISSUE THREAD

**Issue by pourmand1376** [alshedivat/al-folio#1122]
I am considering creating a new repository with support for Hugo instead of Jekyll. I am satisfied with all aspects of this blog, but I am not a fan of Jekyll. I am posting this issue to gauge the level of interest in this idea and determine if it is worth further exploration.

**Comment by rohandebsarkar** [comment]
Since this is not an bug or enhancement, rather it is to see if people are interested on a port to a different framework and probably out of scope for this repository, I am converting this to a discussion.

PS: It will be very interesting to see a Hugo port of `al-folio`. I have previously thought making a port myself but held back as it might not have such a interested user base.
