### ISSUE TITLE
Always get back to the previous branch when deploying. 

### ISSUE THREAD

**Issue by yongwanlim** [alshedivat/al-folio#128]
**Is your feature request related to a problem? Please describe.**
I am struggling with a bug when running ./bin/deploy --user but not sure how to fix it. 

The issue that I have faced is that after I add a new publication into papers.bib and run ./bin/deploy --user, I always end up having the previous version of papers.bib file without any update. Some times, the update is working fine but sometimes I always get back to the previously built version. 

Does anyone have a similar experience or have a solution to it? Thank you so much in advance.

**Comment by alshedivat** [comment]
Do you commit the changes before running deploy? Uncommitted changes are not being saved by the deploy script.

**Comment by yongwanlim** [comment]
Yes, I "add" and "commit" the changes before running deploy...

**Comment by saeed1262** [comment]
@yongwanlim You should add the year of your publication to the years list in https://github.com/alshedivat/al-folio/blob/master/_pages/publications.md if you haven't

**Comment by yongwanlim** [comment]
@saeed1262, thanks for your comment. Yes, I did. 

I have the issue in general. The publication was one example. I am not able to update anything from the previous version. It used to work and this time not... Thanks for your comment!

**Comment by alshedivat** [comment]
Interesting and strange it doesn't work. To better understand this, is it correct that you add a new commit to the `source` branch, then you run `./bin/deploy --user`, and it somehow erases the commit from `source` after deployment? I'm surprised it does something like that, because the script simply switches between `source` and `master`, without editing your commit history... Could you post your git history (use `git log`) before and after running the deploy script?

**Comment by yongwanlim** [comment]
@alshedivat Thank you for your comment. After reading your comment, I realized that I made a really stupid mistake -- I add a new commit to `master` branch, not to `source` branch. After adding a commit to the source and running `./bin/deploy --user`, everything works normal. Thank you for looking into this and providing the feedback!
