### ISSUE TITLE
Force updating cached style files

### ISSUE THREAD

**Issue by Lodour** [alshedivat/al-folio#1395]
**Is your feature request related to a problem? Please describe.**
After updating the style file `main.css`, the browser may not update its cached older version of this style file.

**Describe the solution you'd like**
Adding a hash of the file content as the query string to the style file, like `main.css?xxxmd5hashxxx`.

**Describe alternatives you've considered**
It is possible to version the file with build time by `main.css?{{ site.time }}`, but that would force an update even when the style file was not modified.

**Additional context**
The modification would apply to the head template:
https://github.com/alshedivat/al-folio/blob/c1112d7e71c12572bb92ec082055ba28faa9e1b6/_includes/head.html#L30

EDIT: After some investigation, I find it tricky to implement this. Because the Jekyll filter might render before the sass preprocessor. Maybe using the `{{ site.time }}` would be better, otherwise it is more like a separate plugin beyond this repo.

**Comment by george-gca** [comment]
This can be solved client side with a simple Shift + F5 on Google Chrome, to force update ignoring cache. Now, implementing this on the template seems kind of difficult.

**Comment by Lodour** [comment]
Thanks for the response. I agree that implementing this is hard. I think we can close this issue if you feel the `{{ site.time }}` feature is unnecessary at this point.

But for the Shift + F5 solution, the main issue is that the visitors won't do that when they are not aware of the updated style files.

**Comment by george-gca** [comment]
I agree that the visitors are not aware of the updated styles, but will the changes in the css files be that often? I mean, the changes might not happen that much to make this a burden.

Also, out of curiosity, how usually this situation is handled in other sites? Idk.

**Comment by Lodour** [comment]
Yea the change won't be that often. I found this problem when I was frequently testing styles in deployment.

I think other sites usually version the CSS files with a number or its hash, as far as I can tell from https://stackoverflow.com/questions/1922910/force-browser-to-clear-cache

**Comment by george-gca** [comment]
Found [this post](https://ultimatecourses.com/blog/cache-busting-jekyll-github-pages) that implements exactly what you said about a timestamp. But I believe a more elegant approach would be to calculate a hash from the file, since between updates to your site the css and js files might not get changed.

I found [this plugin](https://github.com/n13org/jekyll-kw-sri) that could be used for this, but could not make it work. Also tried getting the base code from [here](https://github.com/vcsjones/vcsjones.dev/blob/main/_plugins/sri.rb), but to no avail.

**Comment by SanabilQureshi** [comment]
Glad to see that this issue has been raised, very much interested in a potential solution even if it's a temporary one that wouldn't necessarily be pushed to the main repo.

For context, I'm serving the site locally and using a reverse-proxy with Cloudflare to host it under my domain (as a *.domainname.com address). This may be specific to me (although I doubt so since the docker + reverse proxy self-hosting method is very common), but I have found that the css styling changes only take effect locally and not on the *.domainname.com address, unless I make a change to the baseurl parameter and restart the container. I'm guessing this is because the browser is forced to download a fresh cache for the website since the pages no longer exist at their previous location.

Since I'm in the process of customising the al-folio theme to make it a personal website, I frequently make changes to the css styling (only really the max_width parameter) and I can only see those adjustments take effect locally. If I've loaded the public version and then make changes, they do not appear when accessing via the *.domainname.com address.

Shift + F5 is a potential solution, however as mentioned above it's unlikely that the average user will do that. I've even deleted all site/cookies/cache data on a separate browser and then tried accessing the site and even still it seldom applies the new changes.

I've tried to get cache-busting to work but to no avail (probably a lack of understanding on my part)

Using the following bookmarklet will temporarily apply the new css even on the public version, however navigating to any other page immediately reverses it:

`javascript:{let e=(e,t=document)=>Array.from(t.querySelectorAll(e)),t=r=>{for(let t of e('link[rel=stylesheet][href]',r)){let e=new URL(t.href);e.searchParams.set('forceReload',Date.now()),t.href=e}for(let o of e('iframe',r))o.contentDocument&&t(o.contentDocument)};t()}`

If anyone could help suggest even a temporary solution that would be incredible! Many thanks to Lodour for raising the issue, I've spent days trying to resolve it and was planning on creating a new issue/stack-overflow post about it myself.
