### ISSUE TITLE
Support for wide screen

### ISSUE THREAD

**Issue by deng-cy** [alshedivat/al-folio#143]
**Is your feature request related to a problem? Please describe.**
Currently the website is narrow even on a wide screen. 

**Describe the solution you'd like**
I hope there is a feature to extend the width of the pages.

**Comment by alshedivat** [comment]
Thanks for the suggestion, @deng-cy.

Could you provide more details on how you would want the webpage to behave on wide screens? Right now, the theme is designed to have max-width (similar to [distill.pub](https://distill.pub/)), since it would look weird if it was to span the full screen on wide displays.

If you have links to other websites with similar layouts as al-folio which extend to the width of the page on wide displays, please let me know and I'll think if we can add that as an optional layout to al-folio.

**Comment by deng-cy** [comment]
Some page types look good even if it spans the full screen. One option is to set a maximum width in `_config.yml`.

**Comment by ziruizhuang** [comment]
One workaround is to manually adjust the value `$max-content-width: 800px;` in `_sass\_variables.scss`. 
But yes it would be nice if there is an option in `_config.yml` as well.

**Comment by rohandebsarkar** [comment]
`max_width` configuration in the `_config.yml` file does not apply to distill themed blog posts.
