### ISSUE TITLE
Error: Format of generated html files

### ISSUE THREAD

**Issue by DoHaiSon** [alshedivat/al-folio#1434]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
I tried to upgrade my homepage to the latest commit of al-folio. Everything worked fine. However, I realized that all generated HTML files were in the wrong format. The content of these files is in-line and cannot be read without re-format.

- The source: 
[https://github.com/DoHaiSon/dohaison.github.io/tree/source](https://github.com/DoHaiSon/dohaison.github.io/tree/source
)
The output HTML misformatted:
[https://github.com/DoHaiSon/dohaison.github.io/blob/gh-pages/index.html](https://github.com/DoHaiSon/dohaison.github.io/blob/gh-pages/index.html)

**System (please complete the following information):**
 - OS: Ubuntu 20.04 WSL2

**Comment by george-gca** [comment]
What you mean by cannot be read without re-format? By a human?

If so, this is not a problem, since this html file is supposed to be served on `gh-pages` (as can be seen in the misformatted url). The main focus of this html is NOT to be human readable. Even so, a file with less spaces and line breaks have less characters, and consequently less file size. It might not be too much of a difference here, but that is the whole point of existing [minified versions](https://www.cloudflare.com/learning/performance/why-minify-javascript-code/) of commonly used libraries.

**Comment by DoHaiSon** [comment]
Oh, I see. So, if you confirm that this format is what we did on purpose, I agree with you.

I'm sorry, I missed this update changelog of al-folio.

**Comment by george-gca** [comment]
I can't assure you that this change in spacing is made on purpose, either by our side (if it is, idk where) or by the jekyll build process (I looked for it, but couldn't find anything). I just said that it doesn't matter, since this html is not supposed to be read by humans.
