### ISSUE TITLE
Adding giscus comments to project pages

### ISSUE THREAD

**Issue by kshiteesh** [alshedivat/al-folio#1586]
The current documentation mentions how to add giscus comments to blog posts, but I'd like to add them to any page on the website, specifically, project pages.

I added `giscus: true` to my project page and did the rest of the setup in `_config.yml` but it does not seem to work.

**Comment by george-gca** [comment]
It is because the giscus comments are only implemented in the [post layout](https://github.com/alshedivat/al-folio/blob/master/_layouts/post.html). A [project](https://github.com/alshedivat/al-folio/blob/master/_projects/1_project.md?plain=1) uses the `page` layout, as you can see in the front matter, while [blog posts](https://github.com/alshedivat/al-folio/blob/master/_posts/2015-03-15-formatting-and-links.md?plain=1) use `post` as layout. But I agree, this will be a good addition.

**Comment by DavidKrassnig** [comment]
PR #1596 should solve this
