### ISSUE TITLE
sub-menus?

### ISSUE THREAD

**Issue by CarlosGrohmann** [alshedivat/al-folio#159]
Is there any way to get sub-menus on the top navbar with al-folio? Something similar to what [Beautiful Jekyll](https://beautifuljekyll.com/) offers, where one can hover the menu and the sub-menus will drop down. 
Thanks

**Comment by alshedivat** [comment]
@CarlosGrohmann, thanks for the suggestion. As of now, the theme does not support sub-menus. This is partly because we assume that all pages are on the same "level" (i.e., we do not allow some pages to be sub-pages of other pages).

Adding sub-menus would require assuming a hierarchical structure of the pages (e.g., we can assign each page a `parent`; for the upper-level pages, the `parent` will be set `root` or something like that).

If there is a strong use case for this, I'll consider adding this enhancement in a later version of al-folio, or someone from the community could perhaps implement it and send a PR faster.

**Comment by CarlosGrohmann** [comment]
Ok Thanks!

**Comment by alshedivat** [comment]
I'll keep this issue open as a feature request.

**Comment by adib2149** [comment]
I was also looking for this feature to add to my website. I have added a PR, hope this helps!
