### ISSUE TITLE
ERROR: Liquid Exception 

### ISSUE THREAD

**Issue by berzentine** [alshedivat/al-folio#16]
I keep getting this error when I deploy it `Liquid Exception: uninitialized constant ActiveSupport::Multibyte::Chars::Unicode in _pages/publications.md`

**Comment by alshedivat** [comment]
Thanks for reporting this. Could you perhaps provide some more info on the context in which you get this exception? Is it while following the setup instructions in the README?

**Comment by alshedivat** [comment]
Closing due to no response.

**Comment by giograno** [comment]
Hi, I am having the same issue.
Basically, it happens when I try to deploy with `./bin/deploy --user`.
If I try with the following command `jekyll serve --trace --verbose` I get the following error:

```
/Users/grano/.rvm/gems/ruby-2.4.1/gems/jekyll-scholar-5.14.0/lib/jekyll/scholar/utilities.rb:125:in `bibtex_files': undefined method `include?' for nil:NilClass (NoMethodError)
	from /Users/grano/.rvm/gems/ruby-2.4.1/gems/jekyll-scholar-5.14.0/lib/jekyll/scholar/utilities.rb:148:in `bibtex_paths'
```
 that basically points out to the following portion of code:

```
  def bibtex_files
    if config['bibliography'].include? '*'
      @bibtex_files ||= Dir.glob(File.join(config["source"], config['bibliography'])).collect do |f|
        Pathname(f).relative_path_from(Pathname(config['source'])).to_s
      end
    end
    @bibtex_files ||= [config['bibliography']]
  end
```

Many thanks in advance for your help!
