### ISSUE TITLE
How to control the card width in project title page? 

### ISSUE THREAD

**Issue by deng-cy** [alshedivat/al-folio#166]
By default, each card in /projects/ occupy 1/3 of the whole width. Is there any way to adjust this default? In the description, it says " Every project has a beautiful feature showcase page. It’s easy to include images in a flexible 3-column grid format. Make your photos 1/3, 2/3, or full width. " Does it mean I can define the width of each project card?

Right now my solution is to change `width` of `grid-item` in `_base.scss`. But it is fixed for all project cards. I am wondering whether there is any flexible way. Thanks.

**Comment by alshedivat** [comment]
As of now, the project cards have fixed width specified in the `grid-item` class as you pointed out. The description that you are referring to is about the layout of images on the project page, not the project cards.

A more flexible solution would be to define a variable in `_sass/variables.scss` add parameterize the project card width with that variable, so that it can be adjusted easier.

**Comment by deng-cy** [comment]
Got it. Thanks.
