### ISSUE TITLE
New arXiv favicon

### ISSUE THREAD

**Issue by ninyam** [alshedivat/al-folio#1704]
Hi there!

This is not really an issue.
I want my site to display the new arXiv favicon [https://jpswalsh.github.io/academicons/].

But I don't know how to modify the settings to make this possible.

Thanks a lot for your help!

**Comment by george-gca** [comment]
If the icon is already showing somewhere, but it is just not the updated one, all you need to do is update the version of academicon used in [_config.yml](https://github.com/alshedivat/al-folio/blob/81b89c8d454c846eb5b88ccfd2bbf2a556d7ac0b/_config.yml#L380)

**Comment by ninyam** [comment]
Thank you!
I just changed it the 1.9.1 to 1.9.4. However, it didn't work.
I had ORCID, Scopus and arXiv academicons showing with 1.9.1, but when I changed the version they disappeared.

Is this because I also need to change the [integrity](https://github.com/alshedivat/al-folio/blob/81b89c8d454c846eb5b88ccfd2bbf2a556d7ac0b/_config.yml#L381) below version?

Thank you!

**Comment by george-gca** [comment]
Yes, you also have to update the integrity. The integrity is the [hash of the file](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity). With the wrong integrity the file will not load at all.

**Comment by TheFermi0n** [comment]
As you can see [here](https://www.jsdelivr.com/package/npm/academicons), the latest academicons npm package is `1.9.2` and not the `1.9.4`. So you will not be able to get an integrity for `1.9.4`. 

For `1.9.2` the integrity is `"sha256-CylD++oS3IkJmSs/j4i1w0cv2wpVQRLLQqw/m+Fvxts="`

But, the new arXiv icon isn't there as well.

**Comment by george-gca** [comment]
Apparently it's [been a while](https://github.com/jpswalsh/academicons/issues/60) since the npm package was updated. Also there are still missing icons from academicons that could be added (I created a [feature request](https://github.com/jpswalsh/academicons/issues/166) for one a while ago). One day I will create a PR for this.

According to [this site](https://www.cloudflare.com/learning/cdn/cdn-benefits/), it would be better to load things from CDN since it can load from sources closer to the user. At the same time, loading locally can offer other benefits when used with some other solutions like this one [here](https://github.com/alshedivat/al-folio/pull/1562). I will try to do some more thorough tests with the `purgecss` solution, then maybe include it with locally loaded academicons too.

**Comment by george-gca** [comment]
I would for now recommend locally loading the academicons package if you want the latest version. If someone could send a PR for this would be great.

**Comment by george-gca** [comment]
I believe this was fixed in #1562

**Comment by scottleechua** [comment]
Noting here that Academicons on NPM is now be up to date (`v1.9.6`) and future releases will automatically be published to NPM (previously, it was a manual process).

So in case NPM installation is preferred, that option is now available! 👍
