### ISSUE TITLE
Error when try to post to a server

### ISSUE THREAD

**Issue by COD1995** [alshedivat/al-folio#1854]
2:40:50 PM:    Jekyll Diagrams: Command Not Found: mmdc
2:40:51 PM:   Conversion error: JekyllJupyterNotebook::Converter encountered an error while converting "assets/jupyter/blog.ipynb":
2:40:51 PM:                     No such file or directory - jupyter
2:40:51 PM:                     ------------------------------------------------
2:40:51 PM:       Jekyll 4.3.2   Please append `--trace` to the `build` command 
2:40:51 PM:                      for any additional information or backtrace. 
2:40:51 PM:                     ------------------------------------------------

**Comment by george-gca** [comment]
Without a complete stacktrace and a proper description of the steps taken, there is little one can do.

**Comment by COD1995** [comment]
Problem fixed thanks a lot!

**Comment by georginaanna** [comment]
@COD1995 hello, can you advise how you managed to fix this as I am having the same problem?

**Comment by andrewjlock** [comment]
Hi @COD1995, I too have the same issue. Could you please advise how you resolved it?

**Comment by george-gca** [comment]
If your problem is related to `jupyter`, you just need to install it, as stated in the [README](https://github.com/alshedivat/al-folio?tab=readme-ov-file#local-setup-legacy). Note that the recommended way to develop locally is to use [docker](https://github.com/alshedivat/al-folio?tab=readme-ov-file#local-setup-using-docker-recommended).

**Comment by daiqing98** [comment]
> ithout a complete stacktrace and a proper description of the steps taken, there is little one can do.

How is it fixed?
