### ISSUE TITLE
Pinned blog posts not formatting correctly on mobile

### ISSUE THREAD

**Issue by vmasrani** [alshedivat/al-folio#1978]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
 Highlighted blog post cards on mobile are rendered incorrectly (see screenshot)

**To Reproduce**
Make a few blog highlighted blog posts and view on mobile, they are rendered incorrectly (see screenshot)

**Expected behavior**
The cards should be wider

**Screenshots**
![Screenshot_20231204-120951](https://github.com/alshedivat/al-folio/assets/3288149/eaff1c48-afb8-405c-81a7-5a4045ac3795)

**System (please complete the following information):**
 - android, pixel 8pro, chrome browser

**Comment by vmasrani** [comment]
Fixed by changing line 59 in blog/index.html to 
`<div class="row row-cols-1 row-cols-md-{% if featured_posts.size <= 2 or is_even == 0 %}2{% else %}3{% endif %}">`

**Comment by george-gca** [comment]
From the information point of view I believe it should not have that much pinned posts in the blog. Not only because it gets really crowded, but also if all posts are featured, none is really featured, you agree?

Also we are limitting to display at most 2 featured posts per row, I don't understand how yours let it be 3.

**Comment by vmasrani** [comment]
I believe it's from [this](https://github.com/alshedivat/al-folio/blob/6130018c96f721c1783e6e0b9f8da7b4325dbeb6/blog/index.html#L59) line. Looks less crowded when not on mobile, and featured posts bump a few old posts I want to stay on the top

**Comment by george-gca** [comment]
One solution might be using the same limitation we put for the description to the titles, since your titles have too much characters. Other than that, change the number of posts displayed per row in the featured section.

But I don't think this is a bug, since the behavior is correct. The problem is the amount of information you want to display in a section that was thought to display only a couple of posts, and this is a user preference. This template is intended to provide as much as possible ready to use code, but also enable the user to increment it in any way fits their preferences, which I believe is the case here.
