### ISSUE TITLE
Bibliography display issues

### ISSUE THREAD

**Issue by Randl** [alshedivat/al-folio#2070]
**Acknowledge the following**

- [v] I carefully read and followed the [Getting Started](../../README.md#getting-started) guide.
- [v] I read through [FAQ](../../FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [v] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]

**Describe the bug**
After I rebased on latest version, I've noticed to problems with display of bibliography: spaces before commas and different width of badge column for different papers.
I've fixed them in this commit 
https://github.com/Randl/randl.github.io/commit/3ef1b9333385cb60f3e25a0aaea6663023e174a7 
but I'm not sure it's a proper fix.

**Comment by willgearty** [comment]
I think there's an even larger problem here. I've also noticed extra spaces around my last name (on the about page and in the header) and around the individual header items.

**Comment by maximvochten** [comment]
A minimal fix to avoid spaces before commas in the bibliography is to add dashes to 

`{{ author.first }}`
`{{ author.last }}`

so that the lines become 

`{{- author.first }}`
`{{ author.last -}}`

at [this location](https://github.com/alshedivat/al-folio/blob/e430a8949c1fe687ded81fac7786c2872f98f290/_layouts/bib.liquid#L89C1-L90C30).

I also noticed both @willgearty and @Randl have an extra space between their first and last name in the navigation, but I do not experience that problem myself.

**Comment by george-gca** [comment]
I believe some (if not all) of these problems were addressed in #2197

**Comment by willgearty** [comment]
That PR only address the bibliography, not the nav bar and the about me page.
