### ISSUE TITLE
import not found or unreadable: variables.

### ISSUE THREAD

**Issue by brickee** [alshedivat/al-folio#231]
I met an error when running the command "bundle exec jekyll serve". It seems that the main.scss cannot import the file (variables) from _sass.

Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':                     File to import not found or unreadable: variables. Load path: D:/Softwares/Ruby27-x64/lib/ruby/gems/2.7.0/gems/jekyll-theme-primer-0.5.4/_sass on line 7

**Comment by alshedivat** [comment]
Thanks for raising this. Could you please update your ruby to 2.7.2 or newer (3.0.0 should work as well) and try again?

If you run into any issues, please described the steps you took and provide the full error log, otherwise, it's hard to diagnose where the issue is coming from. On my end, installing a fresh ruby 2.7.2 or newer through [rbenv](https://github.com/rbenv/rbenv) and then running `bundle install && bundle exec jekyll serve` works as expected.

**Comment by brickee** [comment]
Thanks very much for responding. The problem has been solved. I guess the reason may be the path problem when I use windows 10. When I change to the subsystem of win10, it works.
