### ISSUE TITLE
Block quote formatting in distill-style posts

### ISSUE THREAD

**Issue by albertfgu** [alshedivat/al-folio#2458]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Block quotes aren't formatted properly in distill-style blog posts

### How to reproduce the bug

The example blog post with block quotes gives this example
```markdown
> ##### TIP
>
> A tip can be used when you want to give advice
> related to a certain content.
{: .block-tip }
```
which is displayed as:
![image](https://github.com/alshedivat/al-folio/assets/8164679/1cdb160d-d5fe-4f7a-a3fc-bbe4fa59cb4c)

However, the same example in a distill-style blog post looks like:
![image](https://github.com/alshedivat/al-folio/assets/8164679/d251189a-ae73-4ae1-9192-52a8a960cb12)

The former looks much better: Ideally at least, block quotes would support headers that are non-italicized and colored.

(Personally, I think that having the entire quote in non-italics is nicer, but at least the header should be formatted)

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Running locally without Docker

**Comment by scottleechua** [comment]
@george-gca hello! 👋 

as a long-time al-folio user I'm looking to start contributing back and want to help with this issue.

I do agree with having formatting consistency between distill and non-distill posts, but this would mean hand-tweaking the CSS in `template.v2.js` and `transforms.v2.js`.

Is this advisable? Are those autogenerated files? Is formatting parity between distill and non-distill a goal for this theme?

**Comment by george-gca** [comment]
I believe at least for the main parts (like code theme, block quote, maybe others) this is advisable. As for hand-tweaking their CSS, maybe we could add a new scss file that will be imported only in the distill layout overriding the specific rules. This way we don't have to mess inside these files, just look at which overrides will be made.

The distill template works as in [this guide](https://distill.pub/guide/), simply by importing these files. These files were probably auto generated a long time ago, since [their repository](https://github.com/distillpub/template) doesn't see an update in years and neither [their site](https://distill.pub/). They even [posted about taking a long hiatus](https://distill.pub/2021/distill-hiatus/). So I think it is safe to say that they won't change for the foreseeable future too.

**Comment by scottleechua** [comment]
Got it! How have you and the maintainers thought about feature parity between the two kinds of post layouts, standard and distill?

For instance, [creating tabs in posts](https://alshedivat.github.io/al-folio/blog/2024/tabs/) works in standard but not distill.

I've had a quick skim of the post features, and the two that make sense to me to support in distill posts are
1) [custom blockquotes](https://alshedivat.github.io/al-folio/blog/2023/custom-blockquotes/), and 
2) [posts that can be cited.](https://alshedivat.github.io/al-folio/blog/2024/post-citation/)

What do you think? I'm happy to open a PR for the two listed above. I just realize it might be good to establish what features are supported where.

**Comment by george-gca** [comment]
I believe it would be useful to support all (if not most) features already implemented for regular posts in the distill template, unless it conflicts with it (for example, the table of contents, or we can have another look at it). At least I see the distill template as a basic template that we shoould customize as we wish.

What do you guys thin @alshedivat, @pourmand1376?
