### ISSUE TITLE
Automate external posts update

### ISSUE THREAD

**Issue by amztc34283** [alshedivat/al-folio#2535]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

I added some posts in my medium blog but they are not appearing in my site:
https://amztc34283.github.io/blog/

### Pitch

It looks like the web page is server-rendered so we probably have to figure out a way to pull update blog posts dynamically.

### Alternatives

Open to discussion and suggestions.

**Comment by george-gca** [comment]
The external posts are fetched during build, so if a new build is not triggered, they will not be fetched. If your posts are not that frequent on medium, the easiest solution is to manually trigger the build action every time you post new content there. As for the client side solution, not really sure if I like the idea. Since you post mainly content in there, wouldn't it be better to rather link the blog directly to your medium?

**Comment by amztc34283** [comment]
Hey @george-gca, it turns out the Medium rss url has a limit of number of posts shown.

I am thinking about adding an optional script to call Medium API and transform the output into a format similar to what rss url would return.

This way, we don't need to store user's credentials inside the Docker and people do not care about the medium posts can opt-out.

Let me know what you think!

**Comment by george-gca** [comment]
> I am thinking about adding an optional script to call Medium API and transform the output into a format similar to what rss url would return.
> 
> This way, we don't need to store user's credentials inside the Docker and people do not care about the medium posts can opt-out.

How would this work?
