### ISSUE TITLE
Github cards stopped working

### ISSUE THREAD

**Issue by fermofou** [alshedivat/al-folio#2625]
### Have you checked that your issue isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/master/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [X] Yes, I have checked that this issue isn't already filed.

### Bug description

Github cards stopped working (user, repo, trophies)

### How to reproduce the bug

Just open the repositories page, i guess it's more of a change in the  required format for the api.
![image](https://github.com/user-attachments/assets/24cc59e6-4241-4d8f-ac3f-d51b1e9ed933)

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Windows, Not applicable (e.g. you're using GitHub Pages or other hosting)

### Where are you seeing the problem on?

Deployed site

**Comment by emigmo** [comment]
me too

**Comment by george-gca** [comment]
This is due to a token limit in the GitHub API. For more information, see [GitHub Readme Stats](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) readme and related issues:
- https://github.com/anuraghazra/github-readme-stats/issues/1471
- https://github.com/ryo-ma/github-profile-trophy/issues/150
- https://github.com/ryo-ma/github-profile-trophy/issues/141
- https://github.com/ryo-ma/github-profile-trophy/issues/145

**Comment by george-gca** [comment]
Basically there is nothing we can do. What you can do is host your own instance of these solutions, as suggested in [GitHub Readme Stats](https://github.com/anuraghazra/github-readme-stats?tab=readme-ov-file#deploy-on-your-own) readme.
