### ISSUE TITLE
UI improvement with design principles

### ISSUE THREAD

**Issue by siddakbagga13** [alshedivat/al-folio#2818]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

Hey @alshedivat please assign it to me and add hacktoberfest tag to it

### Pitch

I will improve the UI and ensure that all the design principle must follow

### Alternatives

I can make the Designing part if other things I find necessary

**Comment by george-gca** [comment]
> Hey @alshedivat please assign it to me and add hacktoberfest tag to it

Since the `hacktoberfest` was added in #2744, is this necessary? I mean, what is the benefit of assigning the issue? I am not aware if this changes anything, but I am curious.

> I will improve the UI and ensure that all the design principle must follow

Can you elaborate it a bit more, like how are you going to improve the UI?

Also depending on the changes, I believe it would be a very good idea to finish the job started in #741 and update some libraries like `bootstrap` withou breaking the UI, but easier said than done.
