### ISSUE TITLE
Responsive custom social icon

### ISSUE THREAD

**Issue by le-hoang-ha-my** [alshedivat/al-folio#2905]
### Have you checked that your feature request isn't already filed?

- [X] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my feature request.
- [X] Yes, I have checked that this feature request isn't already filed.

### Description & Motivation

Currently, the custom social icon only supports png, jpg, and svg. I'm trying to use an icon not defined in Academicons or Font Awesome, and created my own ttf/woff file. It would be nice to support custom icons responsive to light/dark theme and hover effects like the existing icons, given the user's own ttf/woff file.

**Comment by george-gca** [comment]
This has to be done manually, since it involves a lot of changes that I can't see how to make it automated. You can check how it was done for example when we [added Tabler icons](https://github.com/alshedivat/al-folio/pull/2261/files) to our repository. But let me walk you through the steps.

1. Supposing your font have scss files, create a directory for your fonts scss files under `_sass/YOUR_FONT/`, like done with Tabler icons in [_sass/tabler-icons/](https://github.com/alshedivat/al-folio/tree/main/_sass/tabler-icons)
2. Also add your font files to our repo. They'll be located somewhere under `assets/`, like [assets/fonts/](https://github.com/alshedivat/al-folio/tree/main/assets/fonts)
3. You'll have to import them in `assets/css/main.scss`, where we import all our scss

https://github.com/alshedivat/al-folio/blob/cc0cb3c426a66b96cdd01a1b5ba22789612fdaae/assets/css/main.scss#L22-L24

4. Maybe you'll have to set a path to where to load the fonts from. Both Tabler icons and Fontawesome have such a variable, but Academicons not. For example, for Tabler icons by default is

https://github.com/alshedivat/al-folio/blob/cc0cb3c426a66b96cdd01a1b5ba22789612fdaae/_sass/tabler-icons/tabler-icons.scss#L7

But we set it to

https://github.com/alshedivat/al-folio/blob/cc0cb3c426a66b96cdd01a1b5ba22789612fdaae/_sass/_variables.scss#L43-L44

**Comment by le-hoang-ha-my** [comment]
> 4\. the fonts from. Both Tabler icons and Fontawesome have such a variable, but Academicons not. For example, for Ta

I created my own font file instead of pulling from an external source like Fontawesome, can it be in ttf file format or does it have to be scss?

**Comment by george-gca** [comment]
We currently only use Tabler icons in one place, the light/dark theme switch. We do it like this:

https://github.com/alshedivat/al-folio/blob/ec7d7c34e8f1a7ef4da2ea37454f470b8b37094b/_includes/header.liquid#L132

Just use a line similar to this referrent to the icon of your choice.

**Comment by le-hoang-ha-my** [comment]
Solved. Thank you!

**Comment by le-hoang-ha-my** [comment]
Solved. Thank you!

**Comment by le-hoang-ha-my** [comment]
Solved. Thank you!
