### ISSUE TITLE
Your site is having problems building: The tag twitter on line 5 in _posts/2020-09-28-twitter.md is not a recognized Liquid tag.

### ISSUE THREAD

**Issue by hetp111** [alshedivat/al-folio#315]
Here's what I did:

copied al-folio to my repo and pushed it.

And I get this error on the pages tab:

![image](https://user-images.githubusercontent.com/17962201/122047781-27ea8400-cdfe-11eb-9ffa-baea09049f90.png)

**Comment by Quantumstud** [comment]
Hello,
Is there any solution to this?

**Comment by hetp111** [comment]
@Quantumstud By looking at your website it seems like you fixed it. Can you tell how?

**Comment by Quantumstud** [comment]
Hi @hetp111. You have to set the publishing branch to gh-pages rather than main. I had missed this in the original readme,
 
 "Finally, in the Settings, in the Pages section, set the branch to gh-pages (NOT to master). See Configuring a publishing source for your GitHub Pages site for more details."

After setting this my website started working. I hope it helps.

**Comment by hetp111** [comment]
@Quantumstud, I don't see the "gh-pages" branch. Can you gh-pages help?
