### ISSUE TITLE
Jekyll execution issue (nokogiri not found)

### ISSUE THREAD

**Issue by pgg1610** [alshedivat/al-folio#338]
**Acknowledge the following**
- [x] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [x] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please use [gitter chat](https://gitter.im/alshedivat/al-folio) instead of raising an issue.]

**Describe the bug**

**To Reproduce**
1. Go to cloned `al-folio` repo 
2. Execute the setup commands: 
```bash
$ bundle install
$ bundle exec jekyll serve
```

Get nokogiri error on last command: 
```
/Library/Ruby/Gems/2.6.0/gems/nokogiri-1.11.7-arm64-darwin/lib/nokogiri/extension.rb:25:in `require': cannot load such file -- nokogiri/nokogiri (LoadError)
```

Calling just `jekyll` in the command line give the same error. 

I dont get this error outside of the repo folder. 

**Expected behavior**
Setup the Jekyll website environment 

**Screenshots**

[Jekyll error](https://www.dropbox.com/s/fwuks708e9e41s8/Screen%20Shot%202021-07-06%20at%203.50.51%20PM.png?dl=0)

[Expected Output](https://www.dropbox.com/s/623qjo4oifk1ybp/Screen%20Shot%202021-07-06%20at%203.52.49%20PM.png?dl=0)

**System (please complete the following information):**
 - MacOS Big Sur 11.4
 - Jekyll version 4.2.0
 - Ruby version 2.6.3p62 (2019-04-16 revision 67580)

**Comment by Subram0212** [comment]
Hello Everyone,
I am also facing the same issue when I tried to execute the command `bundle exec jekyll serve` within this repo.
The expected behavior was to launch the localhost to view the website but I am unable to do so. Can anyone help me in resolving this issue?

System:
macOS Big Sur 11.2.3
Jekyll version 4.2.0

**Comment by alshedivat** [comment]
related issues: #240 and #250.

generally, people have been able to resolve them by using [rbenv](https://github.com/rbenv/rbenv) and/or switching the ruby version to 2.7.x. it should work however with ruby 3.0.x as well (there were some initial issues when ruby 3 just came out).

**Comment by pgg1610** [comment]
Hello, I was able to solve the problem by deleting one of the two nokogiri version entry. I kept `nokogiri (1.11.7-x86_64-darwin)` this in the file and removed the other one. Not sure if it is the right way to do it but could not figure any other way. Would love any inputs on this.

**Comment by dw61** [comment]
I am running Big Sur on an intel chip Mac. Therefore I should use the x86_64 version of nokogiri instead of the arm64 version. As of the current version (182th commit) of al-folio, I changed the `nokogiri (1.12.3-arm64-darwin)` entry on the 110th line of `Gemfile.lock` file to `nokogiri (1.12.3-x86_64-darwin)` and was able to run `bundle exec jekyll serve`.

**Comment by pourmand1376** [comment]
If you still face this problem, I think you should give `docker` installation a try. It should work just fine.
