### ISSUE TITLE
`{{` is causing error in LaTeX equations

### ISSUE THREAD

**Issue by pkjkrai66** [alshedivat/al-folio#361]
**Acknowledge the following**
- [* ] I carefully read and followed the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide.
- [* ] I read through [FAQ](https://github.com/alshedivat/al-folio#faq) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [ *] The issue I am raising is a potential bug in al-folio and not just a usage question. <br> [For usage questions, please post in the [Discussions](https://github.com/alshedivat/al-folio/discussions) instead of raising an issue.]
-----------------------------------------------------------------------------------------

**Describe the bug**
I have forked & cloned this repository for a technical article. I was writing and compiling an equation when I faced this issue. 

`$$ {{\mathbf{x}}_i } $$` is a legitimate LaTeX command, it could be verified by pasting [here](https://latex.codecogs.com/eqneditor/editor.php). 
But the above syntex gave error with this theme. I have experimented with a couple of combinations and realized that the `{{` is causing the error. In the following, Expression 4 and 5 cause the error. 

```
Expression 1: `$$ {\mathbf{x}}_i $$` --> $$ {\mathbf{x}}_i $$

Expression 2: `$$ { {\mathbf{x}}_i } $$` --> $$ { {\mathbf{x}}_i } $$

Expression 3: `$$ { {\mathbf{x}}_i} $$` --> $$ { {\mathbf{x}}_i} $$

Expression 4: `$$ {{\mathbf{x}}_i } $$` --> $$ {{\mathbf{x}}_i } $$
```
Screenshot of output:

![Jekyll error2](https://user-images.githubusercontent.com/19630517/129095336-20e3032b-5f77-4457-814d-82b425e74377.png)

I receive the following when I compile the website with `bundle exec jekyll server`
```
Configuration file: /home/Website-al-folio-master/al-folio/_config.yml
            Source: /home/Website-al-folio-master/al-folio
       Destination: /home/Website-al-folio-master/al-folio/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Jekyll Feed: Generating feed for posts
         AutoPages: Disabled/Not configured in site.config.
        Pagination: Complete, processed 1 pagination page(s)
    Liquid Warning: Liquid syntax error (line 9): Unexpected character \ in "{{\mathbf{x}}" in /home/Website-al-folio-master/al-folio/_posts/2015-10-20-math.md
    Liquid Warning: Liquid syntax error (line 9): Unexpected character \ in "{{\mathbf{x}}" in /home/Website-al-folio-master/al-folio/_posts/2015-10-20-math.md
    Liquid Warning: Liquid syntax error (line 11): Unexpected character \ in "{{\mathbf{x}}" in /home/Website-al-folio-master/al-folio/_posts/2015-10-20-math.md
    Liquid Warning: Liquid syntax error (line 11): Unexpected character \ in "{{\mathbf{x}}" in /home/Website-al-folio-master/al-folio/_posts/2015-10-20-math.md
                    done in 2.251 seconds.
 Auto-regeneration: enabled for '/home/Website-al-folio-master/al-folio'
    Server address: http://127.0.0.1:4000/al-folio/
  Server running... press ctrl-c to stop. 
```

**Comment by alshedivat** [comment]
@pkjkrai66, thanks for reporting this. the behavior is expected for any Jekyll-built website, not just this theme.

`{{` and `}}` are special characters in Jekyll, which indicate that expressions enclosed between `{{ ... }}` must be evaluated during the website build phase. in your case, Jekyll tries to evaluate `{{\mathbf{x}}` during the build phase an issues warnings that it cannot evaluate the expression (see the warnings in your build log). in the end, it looks like it converts `{{\mathbf{x}}` to an empty string. after the website is built, when you load your webpage, MathJAX tries to evaluate expressions enclosed in `$$ ... $$`, but since `{{\mathbf{x}}` part has been "eaten out" during the build process, MathJAX sees is only `_i }`, which is invalid LaTeX. therefore you get rendering errors.

as you noted, simply adding a space between the double braces (i.e., `{{` -> `{ {`) should solve the problem.
