### ISSUE TITLE
Reverse bibliography order

### ISSUE THREAD

**Issue by bradyrx** [alshedivat/al-folio#47]
Is there an easy way to reverse the bibliography order? It's currently posting it in order from oldest -> newest publications. I'd like my most recent publications at the top. I tried adding `order: descending` and `order: ascending` to the `_config.yml` and nothing changed. I also tried reversing the loop in `_layouts/bib.html` by adding `{% for author in entry.author_array  reversed %}` with no change either.

**Comment by samfearn** [comment]
I don't have time to properly check this at the moment, but following the examples for `reverse` in the docs (https://shopify.github.io/liquid/filters/reverse/), you probably need to change the loop you mentioned in `_layouts/bib.html` to `{% for author in entry.author_array | reverse %}`.

**Comment by bradyrx** [comment]
That doesn't do the trick @samfearn, but I appreciate the link to the liquid API. I think I've gotten a little confused with what notation is what language here, since my background is more down the line of python, etc. I've just been inferring syntax from various files here, so maybe I'll discover something here in the liquid documentation that will help.

Currently changing the `jekyll-scholar` order in the config file + adding `| reverse` is not doing the trick so there might be a hard lock on order somewhere else I need to find.

**Comment by samfearn** [comment]
Liquid is a templating engine, used to template sections of html using loops, variables and so on. The key thing to look for to identify liquid tags are the curly braces inside the markdown files, such as `{% stuff %}` and `{{ stuff }}`. Essentially, those with the percentage signs indicate control flow, and those without are defined objects.

The other file that we've mentioned, `_config.yml` is a YAML file, which essentially stores a load of metadata relative to your site. YAML is also used at the top of each markdown file which Jekyll processes -- the section at the top of each markdown file which is delimited by triple hyphens is also YAML. These YAML variables, either defined in the page metadata at the top of a given page, or in the `_config.yml` file, can then be accessed by liquid using, for example, `{{ page.title }}`, which would be replaced by the YAML variable called title on the given page.

Now, regarding what you're actually trying to do, are you already loading your own `.bib` file? and what order does it appear in currently? Because in the [template files provided](https://alshedivat.github.io/al-folio/publications/), the publications already appear newest first.

**Comment by jenniferisasi** [comment]
I was able to reverse the order by changing the order on the publications.md file YAML 
Instead of 

`years: [2016, 2017, 2018] `

that I did first following the example, I did 
`years: [2018, 2017, 2016]`

and now it displays from newest to oldest

**Comment by bradyrx** [comment]
Thank you @jenniferisasi, this solution worked. I can't believe I didn't think about trying it this way. Sorry @samfearn -- it's been a travel-heavy summer and fall and had to abandon the website development for a bit.
