### ISSUE TITLE
Github Build failed

### ISSUE THREAD

**Issue by sambaiga** [alshedivat/al-folio#5]
I managed to fork this repo and customize to my site need, everything is working fine while local.. but when I deploy the site a  get the following error.

he page build failed for the `master` branch with the following error:

The tag `bibliography` on line 6 in `_pages/publications.md` is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error/.

Kindly, help

**Comment by alshedivat** [comment]
This theme doesn't support the standard deployment method provided by github pages because the latter doesn't support `jekyll-scholar` plugin (here is [their list of supported plugins](https://pages.github.com/versions/)).

This theme has a custom deployment script in `bin/deploy`. It assumes that you are using [bundler](https://bundler.io) to manage your gems. Make sure you edit [line 18](https://github.com/alshedivat/al-folio/blob/master/bin/deploy#L18) of the script if you have a different ruby setup.
