### ISSUE TITLE
Social icons not showing

### ISSUE THREAD

**Issue by nasifimtiazohi** [alshedivat/al-folio#54]
I changed social icons to be true in the config file:

```
show_social_icons:  true
enable_anchorjs:    true
enable_katex:       true
```
However, social icons are not showing. 

![image](https://user-images.githubusercontent.com/31052507/64069539-46778f00-cc19-11e9-816e-8d973119d1b2.png)

What to do?

**Comment by lschmalen** [comment]
I have the same issue when showing the site locally:

`show_social_icons:  true
enable_anchorjs:    false
enable_katex:       true`

When I run `bundle exec jekyll serve` I get the following:
![Screenshot from 2019-09-15 13-11-01](https://user-images.githubusercontent.com/49953583/64920678-b01b9f80-d7ba-11e9-8233-ca95b33db756.png)

Operating system is Ubuntu 19.04, browsers tested are Firefox and Chromium. 

Interestingly, when deploying the site to github-pages, the icons show up as expected, it seems to be a merely local issue

**Comment by nasifimtiazohi** [comment]
Yes, for me it's a local issue as well which I realized afterwards. My system in mac OS Mojave 10.14.6 and tested on Chrome.

**Comment by alshedivat** [comment]
It doesn't work locally because `font-awesome` and `academicons` (linked on [lines 24-25](https://github.com/alshedivat/al-folio/blob/master/_includes/hemline.html#L24-L25) in `_includes/hemline.html`) pull fonts from the local folders as if they are URLs. To make icons show locally, you can make the fonts pulled from https://cdnjs.com by changing the above two lines:
```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css" integrity="sha256-zmfNZmXoNWBMemUOo1XUGFfc0ihGGLYdgtJS3KCr/l0=" crossorigin="anonymous" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.6/css/academicons.min.css" integrity="sha256-uFVgMKfistnJAfoCUQigIl+JfUaP47GrRKjf6CTPVmw=" crossorigin="anonymous" />
```
Alternatively, you can probably configure `jekyll serve` to [allow cross-domain fonts](https://zinoui.com/blog/cross-domain-fonts), but I'm not sure how to do that.

**Comment by lschmalen** [comment]
Thanks for proposing this. I will try out later. In fact, the issue seems to be only on the landing page. When I visit "about" by clicking on the link, the social media icons show flawlessy. So it's probably an issue during the first visit. Could it be due to the fact that in the index.html file, the loading of the fonts 
`<link rel="stylesheet" href="http://localhost:4000/assets/css/fontawesome-all.min.css">`
`<link rel="stylesheet" href="http://localhost:4000/assets/css/academicons.min.css">`
appears at the end of the file so that during a first display, the engine doesn't know how to handle them yet?
