### ISSUE TITLE
Editing the content 

### ISSUE THREAD

**Issue by jenniferisasi** [alshedivat/al-folio#58]
First, thanks for creating this beautiful theme!

I am familiar with jekyll and github and I was looking into migrating my current website to this theme. However, when I uploaded them to GitHub to deploy/publish the site, I saw that all was converted into different files on a new _site directory. 

Now my question is, how could I edit my website in the future? Usually I would edit files in their folders and push them to Github, but I am not sure if it will do the same with the _site folder that I have never worked with before. 

Thanks in advance!

**Comment by alshedivat** [comment]
Good question! If you are running the deploy script in the user mode (i.e., you specify the `-u` flag) it does the following steps:

1) Copies your website sources to the `source` branch.
2) Builds the website generating the files in `_site`.
3) Pushes only the files from `_site` to `master`, deleting everything else (pushing `_site` to master is necessary due to the way github serving works).

To edit the website, just switch to `source` in your local repo, edit files, commit changes, and then run `bin/deploy` again -- it'll regenerate the `_site` for you again and push your changes to `master`.

**Comment by jenniferisasi** [comment]
Thanks for the prompt response @alshedivat! Perfect. It makes sense with the branches at I also noticed that they worked differently than what I am used to. I will try to follow this instructions for future edits.
