### ISSUE TITLE
Ability to change default dark/light mode. 

### ISSUE THREAD

**Issue by ssprakhar** [alshedivat/al-folio#633]
**Is your feature request related to a problem? Please describe.**
The default display mode is Dark by default. There is a toggle to switch to Light, but I would prefer the Light to be default (still keeping the toggle feature intact) 

**Describe the solution you'd like**
A config flag to control the default mode. 

**Describe alternatives you've considered**
I disabled dark mode in config, so, website is now Light, but now the toggle button is gone. I would like that to still be present.

**Comment by alshedivat** [comment]
I think there's a bit of a confusion here. the dark mode is not default. the theme "memorizes" the last setting of whoever views the webpage (storing it in the user's browser cache) and uses that setting whenever the website is visited again.

**Comment by rohandebsarkar** [comment]
The default display is not dark mode. The website queries for the preferred color scheme by through the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) option.

If `prefers-color-scheme` is set to `dark` then only the default mode is dark, otherwise the default mode is light.

https://github.com/alshedivat/al-folio/blob/f7274c0dab0aed6b0b1c0d7534779546478d1910/assets/js/theme.js#L55-L57

**Comment by rohandebsarkar** [comment]
There is a minor bug. The default theme was actually always set to light theme without querying about the user preferences.

This should be fixed by #697.
