### ISSUE TITLE
Disabling blog

### ISSUE THREAD

**Issue by nimafazeli** [alshedivat/al-folio#67]
Hi,
Thanks for the great work. 
Sorry this is probably a noob question.

I would like to disable the blog form the website but I could not figure out how.
I tried to add `blog` and `_posts` to `exclude:` in my config file but it only worked partially. The posts do not show up anymore but the *blog* link is still in the navigation bar. How should I remove the *blog* link from the top of the page?
Thanks in advance

**Comment by soumyasanyal** [comment]
In _includes, comment the line in header.html that links to the blog `<a class="page-link" href="{{ '/blog/' | prepend: site.baseurl | prepend: site.url }}">blog</a>`

**Comment by brunovianna** [comment]
If anyone else comes looking for this, now the blog can be disabled on _config.yml by leaving the blog_name line empty

**Comment by ottuba** [comment]
Hi,

related issue:

I would like to **keep** the blog but instead use a different title ("writings"), and accordingly also use the permalink /writings/ (instead of /blog/).

I have made the respective changes in config.yml, header.html, etc. My "writings" page does show on the webpage as intended, but I cannot get the posts + pagination links to consistently redirect to the updated permalinks. Whenever I restart my local setup, the original "blog" folders and links are generated from scratch and automatically inserted back into my site folder, and so the posts + pagination links then again link back to /blog/ instead of /writings/ (e.g., http://localhost:4000/**blog**/2021/distill/ instead of http://localhost:4000/**writings**/2021/distill/).

My current setup can be found in https://github.com/ottuba/github-website – I'd appreciate any help!

**Comment by papkov** [comment]
> If anyone else comes looking for this, now the blog can be disabled on _config.yml by leaving the blog_name line empty

`blog_name` did not work for me, but empying `blog_nav_title` worked.

**Comment by george-gca** [comment]
Answered in #627.
