### ISSUE TITLE
_includes not assigning links correctly

### ISSUE THREAD

**Issue by adamnicholasprice** [alshedivat/al-folio#9]
This may show my nativity, but the html items within the _includes file do not link the correct links within the _site file upon build. See screen shots attached. 
![_includes syntax](https://user-images.githubusercontent.com/29460883/32644732-58171bba-c598-11e7-9a5b-e3f39ad0480b.png)

 
![resulting index.html](https://user-images.githubusercontent.com/29460883/32644737-64046dba-c598-11e7-8b82-7e3ef837ad23.png)

**Comment by adamnicholasprice** [comment]
That is 
```
<a class='page-link" href='{{ /research/' | prepend: site.baseurl | prepend site.url }}">research</a>
```
Does not yield
```
<a class="page-link" href="https://websitenamehere.com/research">research</a>
```

**Comment by monkeywithacupcake** [comment]
A little late @adamnicholasprice , but I think this is because the generated page is "served" and not built. If you run `bundle exec jekyll serve`, it will serve your site locally. 
You can create the correct settings for your site url and baseurl (which you may not need) in the config.yml

```url: https://websitenamehere.com
baseurl: #subpath of your site if needed
```

When you `bundle exec jekyll build`, the site should be correctly inserted.
