### ISSUE TITLE
version dont update ./bin/deploy 

### ISSUE THREAD

**Issue by grjd** [alshedivat/al-folio#92]
Hi I was able to set up this web with al-folio thank you very much.
https://grjd.github.io/
But it is being a very tortuous process, when I modified pages they didnt update, ruby error messages  etc. This is most likely a problem with my own installation but now I am stuck and asking for help.
I have 3 branches in my github for this repo gh-pages, master and old-state (not sure if i need this at all). When I call to deploy i select source as old-state and destination gh-pages, so in old-state is where the "complete" site is. This is the public repo with the 3 branches  https://github.com/grjd/grjd.github.io/tree/gh-pages
 
But local in my com,puter it is left with this 
![CaptureWEBBlog](https://user-images.githubusercontent.com/7142903/84011713-cf74e100-a976-11ea-8b5d-1cb93e27dc17.PNG)

I want to get in my local computer what it is in https://grjd.github.io/
and continue from that point.
I think maybe the ./bin/deploy messes things up, I am a bit confused.

Thank you!
Jaime

**Comment by alshedivat** [comment]
Not sure I understand the question and/or what is going on. I recommend re-installing the theme from scratch from the master branch since it was upgraded this past weekend. Then, carefully go through the [Getting Started](https://github.com/alshedivat/al-folio#getting-started) guide. If you have additional questions, please ask on [gitter chat](https://gitter.im/alshedivat/al-folio). Thanks.
