### ISSUE TITLE
404 There isn't a GitHub Pages site here.

### ISSUE THREAD

**Issue by brendanjmeade** [alshedivat/al-folio#97]
**Describe the bug**
Trying to fork this and use for brendanjmeade.github.io.  Receiving 404

**To Reproduce**
1. Go to 'brendanjmeade.github.io'
2. See 404 error

**Expected behavior**
Website template should appear.

**System (please complete the following information):**
 - MacOS Catalina
 - Chrome and Safari
 - Jekyll version [e.g. 3.8.7]
- Ruby version [e.g. 2.6.5]

**Additional context**
I'm very much a beginner and appreciate the help!

**Comment by alshedivat** [comment]
Did you follow the instructions in [Getting Started](https://github.com/alshedivat/al-folio#getting-started)?

This looks to me more like installation and/or usage-specific question rather than a bug in al-folio. Please avoid raising issues with such questions and ask on [gitter chat](https://gitter.im/alshedivat/al-folio) instead. Thanks.
